# Permalinks
permalink:           pretty

# Setup
title:               renanccastro
tagline:             Continuous learning
url:                 http://renanccastro.tk
paginate:            3
baseurl:             "http://renanccastro.tk"
excerpt_separator:   "<!---excerpt-break-->"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Renan Castro
  url:               https://github.com/renanccastro
  email:             renanccastro@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
